services:
  good_job_repro_db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-16-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: good_job_repro_development
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/good_job_repro
    ports:
      - "3000:3000"
    depends_on:
      - good_job_repro_db
volumes:
  pg-16-dev:
  web:
